name: Deployment to production

on:
  push:
    branches:
      - main

jobs:
  checkout-repository:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.3
      - name: Verificar reglas de eslint
        run: eslint .
